{% set name = "py-plumed-metatomic" %}

# update the dev suffix whenever the git_rev changes
{% set version = "2.10.0.dev0" %}
{% set git_rev = "00b1cc034c3c66d9d18436518e2b1b11d6266843" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/plumed/plumed2.git
  git_rev: {{ git_rev }}
  depth: 1

build:
  number: 1
  skip: true  # [win or py2k]
  string: py{{ CONDA_PY }}_h{{ PKG_HASH }}_git.{{ git_rev[:7] }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - setuptools
    - pip
    - cython
  run:
    - plumed-metatomic {{ version }}
    - python

test:
  imports:
    - plumed
  commands:
    - python -c "import plumed; p=plumed.Plumed(); print(p)"

about:
  home: http://www.plumed.org/
  license: LGPL-3.0
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Python wrappers for plumed library
  description: |
    PLUMED is an open source library for free energy calculations in molecular
    systems which works together with some of the most popular molecular
    dynamics engines. This version enables the metatomic integration.
  doc_url: https://www.plumed.org/doc
  dev_url: https://github.com/plumed/plumed2

extra:
  recipe-maintainers:
    - HaoZeke
    - Luthaf
