github:
  user_or_org: metatensor

github_actions:
  triggers:
  - push
  - pull_request

provider:
  linux_64: github_actions
  osx_64: github_actions
  osx_arm64: github_actions
  linux_aarch64: github_actions
